language: node_js

node_js:
  - "iojs"
  - "7"
addons:
    apt:
      update: true
      packages:
        - oracle-java8-installer  
    sonarqube:
      organization: "gary_corporation"
      token:
        secure: "$SENHA_SONNAR" 

branches:
  only:
  - master
  - desenvolvimento
  
install:
  - npm install

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  
script:
  - npm test
  - sonar-scanner

notifications:
   slack: bsi-ifserra:zMiNFakrxPFZt4wgvFiXXvvw
